MyBlog/forms/myforms.py
from flask_wtf import FlaskForm
from wtforms import SubmitField, StringField, PasswordField, TextAreaField, EmailField
from wtforms.validators import DataRequired, InputRequired


class Form1(FlaskForm):
    author = StringField("Author", validators=[DataRequired(), InputRequired()])
    username = StringField("Username", validators=[DataRequired(), InputRequired()])
    passwd = PasswordField("Password", validators=[DataRequired(), InputRequired()])
    security_question = StringField("Security Question", validators=[DataRequired(), InputRequired()])
    answer = StringField("Answer", validators=[DataRequired(), InputRequired()])
    title = StringField("Title", validators=[DataRequired(), InputRequired()])
    content = TextAreaField("Content", validators=[DataRequired(), InputRequired()])
    subject = StringField("Subject", validators=[DataRequired(), InputRequired()])
    email = EmailField("Author email")
    submit = SubmitField("save")

MyBlog/__init__.py
from flask import Flask
from .routes.myroutes import blog
from .extension import mongo


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = "we are the champions"
    app.config["MONGO_URI"] = "mongodb://localhost:27017/Blog"

    mongo.init_app(app)

    app.register_blueprint(blog)

    return app

MyBlog/routes/myroutes.py
from flask import Blueprint, render_template, redirect, flash, url_for
from MyBlog.extension import mongo
from MyBlog.forms.myforms import Form1
from bson.objectid import ObjectId
from datetime import datetime

blog = Blueprint("blog", __name__)


@blog.route('/')
def home():
    blogger = mongo.db.myFlaskBlog
    blogs = blogger.find()
    return render_template("blogs/home.html", blogs=blogs)


@blog.route('/detail/<blog_id>')
def detail(blog_id):
    blogger = mongo.db.myFlaskBlog
    my_blog = blogger.find_one({"_id": ObjectId(blog_id)})
    view = my_blog["views"] + 1
    blogger.update_one({"_id": ObjectId(blog_id)}, {"$set": {"views": view}})
    myblog = blogger.find_one({"_id": ObjectId(blog_id)})
    print(myblog)
    return render_template("blogs/detail.html", myblog=myblog)


@blog.route('/like/<blog_id>')
def like(blog_id):
    blogger = mongo.db.myFlaskBlog
    my_blog = blogger.find_one({"_id": ObjectId(blog_id)})
    likes = my_blog["like"] + 1
    blogger.update_one({"_id": ObjectId(blog_id)}, {"$set": {"like": likes}})
    return redirect(url_for('blog.home'))


@blog.route('/dislike/<blog_id>')
def dislike(blog_id):
    blogger = mongo.db.myFlaskBlog
    my_blog = blogger.find_one({"_id": ObjectId(blog_id)})
    dislikes = my_blog["dislike"] + 1
    blogger.update_one({"_id": ObjectId(blog_id)}, {"$set": {"dislike": dislikes}})
    return redirect(url_for('blog.home'))


@blog.route('/delete/<blog_id>')
def delete(blog_id):
    blogger = mongo.db.myFlaskBlog
    blogger.delete_one({"_id": ObjectId(blog_id)})
    return redirect("/")


@blog.route('/add', methods=["post", "get"])
def add():
    form = Form1()
    blogger = mongo.db.myFlaskBlog
    if form.validate_on_submit():
        my_dict = {
            "author": form.author.data,
            "title": form.title.data,
            "content": form.content.data,
            "email": form.email.data,
            "date": datetime.utcnow(),
            "views": 0,
            "like": 0,
            "dislike": 0,
            "passwd": form.passwd.data,
            "username": form.username.data,
            "security question": form.security_question.data,
            "answer": form.answer.data,
            "subject": form.subject.data,
        }
        blogger.insert_one(my_dict)
        print(my_dict)
        flash("saved", 201)
        return redirect('/')
    return render_template("blogs/create.html", form=form)


@blog.route('/author')
def author():
    blogger = mongo.db.myFlaskBlog
    blogs = blogger.find()
    authors = list()
    for i in blogs:
        authors.append({"name": i['author'], "username": i["username"], "email": i["email"]})
    return render_template("blogs/author.html", authors=authors)


@blog.route('/author works/<author_name>')
def author_works(author_name):
    blogger = mongo.db.myFlaskBlog
    names = blogger.find()
    data = list()
    subject_matter = list()
    for name in names:
        data.append(
            {
                "_id": name['_id'],
                "author": name['author'],
                "title": name['title'],
                "content": name['content'],
                "subject": name['subject'],
             })
    for i in data:
        if author_name == i['author']:
            subject_matter.append(i)
    return render_template("blogs/author_works.html", subject_matter=subject_matter, author_name=author_name)


@blog.route('/subject works/<subject_title>')
def subject_works(subject_title):
    blogger = mongo.db.myFlaskBlog
    names = blogger.find()
    data = list()
    subject_matter = list()
    for name in names:
        data.append(
            {
                "_id": name['_id'],
                "author": name['author'],
                "title": name['title'],
                "content": name['content'],
                "subject": name['subject'],
             })
    for i in data:
        if subject_title == i['subject']:
            subject_matter.append(i)
    return render_template("blogs/subject_works.html", subject_matter=subject_matter, subject_title=subject_title)


@blog.route('/subject')
def subject():
    blogger = mongo.db.myFlaskBlog
    blogs = blogger.find()
    subjects = list()
    for i in blogs:
        subjects.append(i['subject'])
    subjects = list(set(subjects))
    return render_template("blogs/subject.html", subjects=subjects)


@blog.route('/about')
def about():
    return render_template("about.html")


@blog.errorhandler(404)
def page_not_found(e):
    return e, 404

MyBlog/templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block body %}
    <h1>Background information</h1>
    <p>This is a simple blog project that is used to display some of the flasks capabilities. It is built to do some
    simple things like allow the user to create a blog and display the blog. </p>
    <h1>Author</h1>
    <p>The author of this project is Derrick Wakhu Shibero. At the making of this project, he is currently a second year
    student of computer science. He has worked extensively with the flask framework and can create many things that
    require knowledge in flask. He is currently working on other projects that will eventually put him on the map.
    He also works with the django framework and is interested in machine learning and working with nosql databases like
    mongodb which was used in the creation of this project</p>
    <h1>Features</h1>
    <p>
        <ul>
            <li>Allow user to create a blog</li>
            <li>Allow user to view a blog</li>
            <li>Allow user to like a view</li>
            <li>Allow use to dislike a view</li>
            <li>Allow user to delete a view</li>
            <li>It is built entirely on flask</li>
            <li>The database it uses is mongodb</li>
        </ul>
    </p>
{% endblock %}

MyBlog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta about="this is a blog website">
    <title>Blogs: {% block title %}{% endblock %}</title>
    <link href="{{url_for('static', filename='css/style.css')}}" type="text/css" rel="stylesheet">
</head>
<body>
    <header>
        {% include "header.html" %}
    </header>

    <div class="content">
        <div class="content-block">
            {% block body %}{% endblock %}
        </div>
    </div>

    <footer>
        {% include "footer.html" %}
    </footer>
</body>
</html>

MyBlog/templates/blogs/author.html
{% extends 'base.html' %}

{% block title %}authors{% endblock %}

{% block body %}
    <h1>Authors</h1>
    <table>
        <tr>
            <th>author</th>
            <th>username</th>
            <th>email</th>
        </tr>
        {% for author in authors %}
            <tr>
                <td><a href="{{url_for('blog.author_works', author_name=author.name)}}">{{ author.name }}</a></td>
                <td>{{ author.username }}</td>
                <td>{{ author.email }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

MyBlog/templates/blogs/author_works.html
{% extends 'base.html' %}

{% block title %}by {{ author_name }}{% endblock %}

{% block body %}
<h1>Author: {{ author_name }}</h1>
<ul>
{% for i in subject_matter %}
    <fieldset>
        <legend>{{ i['subject'] }}</legend>
        <dl>
            <dt>{{ i['title'] }}</dt>
            <dd>{{ i['content'][:100] }}... <a href="{{url_for('blog.detail', blog_id=i['_id'])}}">read more</a></dd>
        </dl>
    </fieldset>
{% endfor %}
</ul>
{% endblock %}

MyBlog/templates/blogs/create.html
{% extends 'base.html' %}

{% block title %} create {% endblock %}

{% block body %}
    <form method="post">
        {{ form.hidden_tag() }}
        {{ form.author.label }}<br>{{ form.author() }}<br>
        {{ form.username.label }}<br>{{ form.username() }}<br>
        {{ form.passwd.label }}<br>{{ form.passwd() }}<br>
        {{ form.security_question.label }}<br>{{ form.security_question() }}<br>
        {{ form.answer.label }}<br>{{ form.answer() }}<br>
        {{ form.email.label }}<br>{{ form.email() }}<br>
        {{ form.subject.label }}<br>{{ form.subject() }}<br>
        {{ form.title.label }}<br>{{ form.title() }}<br>
        {{ form.content.label }}{{ form.content() }}<br>
        {{ form.submit() }}
    </form>
{% endblock %}

MyBlog/templates/blogs/detail.html
{% extends 'base.html' %}

{% block title %}{{ myblog.title }}{% endblock %}

{% block body %}
    <h1 id="detail_title">Title: {{ myblog.title }}</h1>
    <h2>Author: {{ myblog.author }}</h2>
    <h3>Email: <a href="{{myblog.email}}">{{ myblog.email }}</a></h3>
    <h3>Date: {{ myblog.date }}</h3>
    <div>
        <fieldset>
            <legend>Content</legend>
            <p id="doc-body">{{ myblog.content }}</p>
        </fieldset>
    </div>
    <div>
        <button><a href="{{url_for('blog.like', blog_id=myblog._id)}}">like</a></button>
        <button><a href="{{url_for('blog.dislike', blog_id=myblog._id)}}">dislike</a></button>
        <button><a href="{{url_for('blog.delete', blog_id=myblog._id)}}">delete</a></button>
        <p><a href="#detail_title">back to top</a></p>
    </div>
{% endblock %}

MyBlog/templates/blogs/home.html
{% extends 'base.html' %}

{% block title %} home {% endblock %}

{% block body %}
    {% for blog in blogs %}
        <div class="single-data">
            <fieldset>
                <legend><a href="{{url_for('blog.subject_works', subject_title=blog.subject)}}" title="Related blogs"><span class="home_subject">{{ blog.subject }}</span></a></legend>
                <div>
                    <p>
                        <span class="home_title">{{ blog.title }}</span> by
                        <a href="{{url_for('blog.author_works', author_name=blog.author)}}" title="Other works by the author"><span class="home_author">{{ blog.author }}</span></a> <hr>
                        {{ blog.content[:120] }}... <a href="{{url_for('blog.detail', blog_id=blog['_id'])}}">read more</a>  <br>
                        views: {{ blog.views }}
                        <a href="{{url_for('blog.like', blog_id=blog._id)}}">like</a>: {{ blog.like }}
                        <a href="{{url_for('blog.dislike', blog_id=blog._id)}}">dislike</a>: {{ blog.dislike }}
                    </p>
                </div>
            </fieldset>
        </div>
    {% endfor %}
{% endblock %}

MyBlog/templates/blogs/subject.html
{% extends 'base.html' %}

{% block title %} Subjects {% endblock %}

{% block body %}
    <h1>Subjects</h1>
    <ul>
        {% for subject in subjects %}
            <li><a href="{{url_for('blog.subject_works', subject_title=subject)}}" title="Related blogs">{{ subject }}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

MyBlog/templates/blogs/subject_works.html
{% extends 'base.html' %}

{% block title %}by {{ subject_title }}{% endblock %}

{% block body %}
<h1>Subject: {{ subject_title }}</h1>
<ul>
{% for i in subject_matter %}
    <fieldset>
        <legend>{{ i['title'] }}</legend>
        <dl>
            <dt>{{ i['author'] }}</dt>
            <dd>{{ i['content'][:100] }}... <a href="{{url_for('blog.detail', blog_id=i['_id'])}}">read more</a></dd>
        </dl>
    </fieldset>
{% endfor %}
</ul>
{% endblock %}

MyBlog/templates/footer.html
<!-- This is the model for the footer. this makes it easier to format as all the code related to the footer is at one place -->
<div class="footer">
    <p>visit us on
        <a href="https://www.reddit.com" title="reddit"><img src="{{url_for('static', filename='images/reddit_dark.svg')}}" height="50" width="50" alt="reddit logo"></a>
        <a href="https://www.twitter.com" title="twitter"><img src="{{url_for('static', filename='images/twitter.svg')}}" height="50" width="50" alt="twitter logo"></a>
        <a href="https://www.facebook.com" title="facebook"><img src="{{url_for('static', filename='images/facebook.svg')}}" height="50" width="50" alt="facebook logo"></a>
        <a href="https://www.pinterest.com" title="pinterest"><img src="{{url_for('static', filename='images/pinterest.svg')}}" height="50" width="50" alt="pinterest logo"></a>
        <a href="https://www.whatsapp.com" title="whatsapp"><img src="{{url_for('static', filename='images/whatsapp_dark.svg')}}" height="50" width="50" alt="whatsapp logo"></a>
        <a href="https://www.youtube.com" title="youtube"><img src="{{url_for('static', filename='images/youtube.svg')}}" height="50" width="50" alt="youtube logo"></a>
        <a href="https://www.instagram.com" title="instagram"><img src="{{url_for('static', filename='images/instagram.svg')}}" height="50" width="50" alt="instagram logo"></a>
        <a href="https://www.gmail.com" title="gmail"><img src="{{url_for('static', filename='images/email.svg')}}" height="50" width="50" alt="email logo"></a>
    </p>
    <p>&copy; 2023 Black&trade;</p>
</div>

MyBlog/templates/header.html
<div class="header">
    <nav>
        <ul>
            <li>MyBlog</li>
            <li><a href="/">Home</a></li>
            <li><a href="/add">Create new</a></li>
            <li><a href="/author">Authors</a></li>
            <li><a href="/subject">Subject</a></li>
            <li><a href="/about">About</a></li>
        </ul>
    </nav>
</div>